/// Flutter icons Custom_icon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom_icon
///      fonts:
///       - asset: fonts/Custom_icon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'Custom_icon';
  static const String? _kFontPkg = null;

  static const IconData logo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData our_service = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top_product = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData top_store = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData near_me = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_amount = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
