/// Flutter icons MandobIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MandobIcons
///      fonts:
///       - asset: fonts/MandobIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MandobIcons {
  MandobIcons._();

  static const _kFontFam = 'MandobIcons';
  static const String? _kFontPkg = null;

  static const IconData logo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
